# Generated by Django 5.1.6 on 2025-02-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='media/products')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('availability', models.CharField(choices=[('available', 'Available'), ('not available', 'Not Available')], default='available', max_length=20)),
            ],
        ),
    ]
